### ISSUE TITLE
Add DAG to doc

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/euro-calliope#108]
Provide a complete overview of repository layout

* All top-level directories and what their purpose is
* Figure(s) of DAG(s)

**Comment by timtroendle** [comment]
The first of the two has always been part of the documentation. Or do you think it requires more work?

**Comment by timtroendle** [comment]
We want this to be automated. First, so that we always generate the same graph. Second, so that we don't forget to update it. This will get easily out of sync if we do not automate it. In the best case, we would not need to check the result in to the Git repository (similar to the built documentation or the built model which are not checked in).

Automating this locally isn't too difficult. I cannot come up with a solution that automates this for Read the Docs. Somehow we needed a hook that generates the DAG just before readthedocs generates the documentation. I fear this hook does not exist. Any ideas? @brynpickering maybe?

Here's the prototype for a solution that works locally. Because Snakemake does not support this natively, it's a bit clunky.

```Python
rule graph_text:
    output: "build/some-file.txt"
    run:
        import io
        from contextlib import redirect_stdout

        graph = io.StringIO()
        with redirect_stdout(graph):
            snakemake.snakemake("/Users/trtim/Develop/euro-calliope/Snakefile", printrulegraph=True)
        with open(output[0], "w") as f_graph:
            f_graph.write(graph.getvalue())


rule graph:
    input: rules.graph_text.output[0]
    conda: "envs/docs.yaml"
    output: "build/some-file.png"
    shell: "cat {input} | dot -Tpng > {output}"
```

**Comment by timtroendle** [comment]
A second best solution would be to keep the rules above so that we can automatically generate it locally. We check the graph in to the Git repository. Then, this must be updated manually as part of our release process (#109).

**Comment by timtroendle** [comment]
The right entry point seems to be the plugin system of mkdocs: https://www.mkdocs.org/dev-guide/plugins/
