### ISSUE TITLE
Split the documentation based on user roles

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#154]
The current documentation is all over the place -- and the new readthedocs documentation (introduced in #106) made that only worse than better I believe (because it exposes a lot of information targeted at developers and advanced users to the public which mainly want to use the pre-builts and don't need this information).

I believe there are three user roles and we should split the documentation based on these roles.

There are **basic users** (no, some, or expert knowledge in Calliope; no or little knowledge in running workflows; some or expert knowledge in energy system modelling). These users want to use the pre-built and they must know about model components, available overrides, and available modules they can import (yaml files).

There are **advanced users** (some or expert knowledge in Calliope; some or expert knowledge in running workflows; some or expert knowledge in energy system modelling). These users want to run the workflow and they must know (in addition) about repo layout, how to run the workflow, how to configure the workflow. They may be interested in using euro-calliope as a subworkflow (and thus a Cookiecutter template https://github.com/timtroendle/cookiecutter-reproducible-research/issues/4).

There are **developers** (expert knowledge in Calliope; some or expert knowledge in workflows; some or expert knowledge in Python development; no, some, or expert knowledge in energy system modelling). These _users_ will send pull requests and they must know about our branching model, testing strategy, and documentation policy.

I may have forgotten things, but this is roughly how I think we should structure the documentation -- in particular the one that is facing the public right now on read the docs.

**Comment by timtroendle** [comment]
@brynpickering @sjpfenninger any comments on this?

**Comment by brynpickering** [comment]
I agree that we should have documentation for different users and those you describe sound sensible. Three broad sections should then cover:

1. How to access and run the Euro-Calliope model (Zenodo link for stable versions + Euro-Calliope model README).
2. How to run the Euro-Calliope workflow to produce a custom / development version of the model.
3. How to use the Euro-Calliope workflow as a sub-workflow.
4. How to contribute to Euro-Calliope workflow development.

The key issue for me is maintaining documentation alongside core development. For `1.` we could use a [Sphinx Jinja2 plugin](https://pypi.org/project/sphinx-jinja/) to render the `templates/README.md` file. The main repo README most closely matches `2.` and I would update that to better match it. Then we just need to maintain documentation for `3.` and `4.`, which are both the least likely to become stale imo.

I wouldn't worry about the current 'public-facing' docs being a massive problem while split documentation is being prepared, since one only accesses them via the link given in this repo's README and they are then just a copy of the README (which is as equally 'public-facing').

**Comment by timtroendle** [comment]
Sounds good to me. Two comments: First, can't we remove almost all documentation from `README.md` and `template/README.md` and instead point to eurocalliope.readthedocs.com? 

Second, are you fine with moving (3) into (2)? To me, it's the same group of people, it's really just another way of running the workflow.

**Comment by brynpickering** [comment]
Point one: certainly. Although we probably still want to package `template/README.md` in the pre-builts.

Point two: I actually see people in (2) as wanting to get into understanding `Euro-Calliope` and are more on the 'some knowledge' part of running workflows. (3) are probably more adept at running workflows if they are considering the possibility of having their own workflow that uses parts of / all of euro-calliope. This is really just a question of sub-sections of the documentation; in either case, the same content would be online.

**Comment by timtroendle** [comment]
Good. I'll give it a try and will let you review once done.
