### ISSUE TITLE
Ensure existing RAMP profiles are appropriate for full electrification

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#287]
### What can be improved?

We currently use [pre-compiled RAMP profiles](https://zenodo.org/record/6579421) for full electrification of small and light electric vehicles (implemented in #271).

This makes only sense, if these profiles represent charging power, not driving power. We nee to ensure that that's the case.

If that's not the case, we need to make necessary changes. Either post process the profiles, create other profiles using RAMP, or document this assumpution (if we think it's not too bad).

### Version

1.2.0.dev

**Comment by brynpickering** [comment]
I believe the two profiles are: 1. % of fleet plugged in and 2. battery electricity use. I.e., neither is "charging power". This is because the sector-coupled model was set up to optimise charging profiles (i.e. utility provider manages a "smart" charging profile covering all EV owners),  so there was no use in the charging power profile. I know RAMP _can_ produce a charging power profile but then you have to decide on the assumptions of how people will charge (unmanaged, i.e. very peaky, or overnight managed, or trickle charging, etc. etc. ). We may have this set of pre-generated profiles lying around somewhere as I know I discussed it with @FLomb.

**Comment by FLomb** [comment]
Hi, yes, what Bryn says is exact. By default, RAMP-mobility does produce charging profiles, but that entails an exogenous assumption on how people charge; in SC-Euro-Calliope, we wanted charging to be instead an endogenous optimisation variable under the assumption of fleets being controllable by aggregators. So, we rather extracted from RAMP the profiles discussed by Bryn and set up custom constraints that would allow us to play with charging flexibility. In follow-up work with @FraSanvit in which we looked at V2G options, endogenous optimisation of charging was even more of a necessity, so we kept going with the same profiles.

It is totally possible to get, as per RAMP's default output, charging profiles for use in a model in which e-mobility demand needs to be accounted for but is assumed non-controllable. The only thing to decide is the assumed share of smart and non-smart charging. In RAMP-mobility's paper (https://doi.org/10.1016/j.apenergy.2022.118676), we assume some plausible shares based on the literature, and we quantify how different the load resulting from completely unmanaged vs partially smart fleets is (see Figs. 6 and 7). While coming up with plausible assumptions about the degrees of smartness of a fleet is doable, such assumptions are inherently uncertain and would, in my opinion, require the generation of many plausible profiles based on different assumptions for sensitivity analysis of any model result relying on those.
