### ISSUE TITLE
conda-frontend: mamba fails from profiles/default

### ISSUE THREAD

**Issue by adrienmellot** [calliope-project/euro-calliope#377]
### What happened?

When running `profiles/conda` snakemake fails and returns the output below.

Two work arounds:
1. Comment the line `condo-frontend: mamba` in `profiles/default/config.yaml`
2. run with `--conda-frontend conda` from the command line

### Version

1.2.0.dev

### Relevant log output

```shell
snakemake --profile profiles/conda --configfile="config/minimal.yaml" all --cores 1
Using profiles profiles/conda and workflow specific profile profiles/default for setting default command line arguments.
Config file config/default.yaml is extended by additional config specified via the command line.
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
CreateCondaEnvironmentException:
The 'mamba' command is not available in the shell /bin/bash that will be used by Snakemake. You have to ensure that it is in your PATH, e.g., first activating the conda base environment with `conda activate base`.The mamba package manager (https://github.com/mamba-org/mamba) is a fast and robust conda replacement. It is the recommended way of using Snakemake's conda integration. It can be installed with `conda install -n base -c conda-forge mamba`. If you still prefer to use conda, you can enforce that by setting `--conda-frontend conda`.
```

**Comment by timtroendle** [comment]
This is a regression introduced in #361

**Comment by timtroendle** [comment]
It is based on the missunderstanding that global profiles aren't overriding workflow profiles, but the other way round. That's why Snakemake is expecting mamba even if the conda profile is chosen.

The easiest solution is Adrien's (1) workaround. Mamba is the default choice of Snakemake, so there is actually no need to explicitly set that parameter value. The intention of setting the value was to be explicit about it and to override any Snakemake defaults but both aren't essential.
